name: deepDiffusion
channels:
  - default
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.20.2
  - tensorflow
  - keras
  - sklearn
  - argparse
  - matplotlib
  - pip:
    - ini-parser
  #   - pyevtk
  #   - matplotlib
  #   - h5py
  #   - numba
  #   - argparse
  #   - scipy
